name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:                 
  DOCKER_REPOSITORY: casino
  DOCKER_REGISTRY: oran901
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
              
    
    - name: Build, tag, and push image to docker hub
      id: build-image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to docker hub so that it can
        # be deployed to EKS.
        pwd
        docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG .
        docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
        echo "image=$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  update-values:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v2
        with:
          repository: Oran901/gitOpsPoke
          token: ${{ secrets.ACCESS_TOKEN }}
          path: gitops
          ref: main

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Update image tag in values.yaml
        run: |
          cd gitops/environments/dev
          yq e '.front.tag = "${{ github.sha }}"' -i values.yaml

      - name: check changes
        run: cat gitops/environments/dev/values.yaml

      - name: Commit and push changes
        run: |
          cd gitops
          git config user.name "Oran901"
          git config user.email "${{ secrets.EMAIL }}"  
          git add .
          git commit -m "Update backend image to ${{ github.sha }}"
          git push